Models/Alojamiento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace tpc5FI.Models
{
    public class Alojamiento
    {
        [Key]
        public int codigo { get; set; }
        [Display(Name = "Tipo alojamiento")]
        public string tipo { get; set; }
        [Display(Name = "Ciudad")]
        public string ciudad { get; set; }
        [Display(Name = "Barrio")]
        public string barrio { get; set; }
        [Display(Name = "Estrellas")]
        public int estrellas { get; set; }
        [Display(Name = "Cantidad de personas")]
        public int cantPersonas { get; set; }
        [Display(Name = "Tiene Tv")]
        public bool tv { get; set; }
        [Display(Name = "Precio por Dia")]
        public double precioxDia { get; set; }
        [Display(Name = "Precio por Persona")]
        public double precioxPersona { get; set; }
        [Display(Name = "Habitaciones")]
        public int habitacion { get; set; }
        [Display(Name = "Baños")]
        public int baño { get; set; }
        [Display(Name = "Ocupado")]
        public bool ocupado { get; set; }

        public Alojamiento()
        {

        }

        public Alojamiento(string ciudad, string barrio, int estrellas, int cantPersonas, bool tv, double precioxDia , double precioxPersona, int habitacion, int baño, bool ocupado,string tipo)
        {
            this.ciudad = ciudad;
            this.barrio = barrio;
            this.estrellas = estrellas;
            this.cantPersonas = cantPersonas;
            this.tv = tv;
            this.precioxDia = precioxDia;
            this.precioxPersona = precioxPersona;
            this.habitacion = habitacion;
            this.baño = baño;
            this.ocupado = ocupado;
            this.tipo = tipo;

        }
    }
}

Controllers/AlojamientoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tp5Fi.Data;
using Newtonsoft.Json;
using tpc5FI.Models;

namespace tp5Fi.Models
{
    public class AlojamientoController : Controller
    {
        private readonly MyContext _context;

        public AlojamientoController(MyContext context)
        {
            _context = context;
        }

        // GET: Alojamiento
        public async Task<IActionResult> Index()
        {
            return View(await _context.Alojamiento.ToListAsync());
        }


        [HttpPost]
        public IActionResult filtrar([Bind("filtrar")] string filtrar, [Bind("mylista")] string mylista)
        {
            List<Alojamiento> mylistaJ = JsonConvert.DeserializeObject<List<Alojamiento>>(mylista);
            System.Diagnostics.Debug.WriteLine("hola ");
            System.Diagnostics.Debug.WriteLine(filtrar);
            //List<Alojamiento> mylistaJ = JsonSerializer.Deserialize(mylista, returnType, default);

            foreach (Alojamiento aloj in mylistaJ)
            {
                System.Diagnostics.Debug.WriteLine("my cidudad " + aloj.ciudad + "barrio " + aloj.barrio + "estrellas " + aloj.estrellas + "precio d " + aloj.precioxDia + "cant  " + aloj.cantPersonas);
            }

            List<Alojamiento> ListaOrdenada = null;
            if (filtrar == "estrellas")
            {
                System.Diagnostics.Debug.WriteLine("estrellas");
                ListaOrdenada = mylistaJ.OrderBy(a => a.estrellas).ToList();
            }
            else if (filtrar == "cantidadPersonas")
            {
                System.Diagnostics.Debug.WriteLine("cantPersonas");
                ListaOrdenada = mylistaJ.OrderBy(a => a.cantPersonas).ToList();
            }
            else if (filtrar == "precioDia")
            {
                ListaOrdenada = mylistaJ.OrderBy(a => a.precioxDia).ToList();
            }
            else if (filtrar == "precioPersona")
            {
                ListaOrdenada = mylistaJ.OrderBy(a => a.precioxPersona).ToList();
            }
            else if (filtrar == "maxPrecio")
            {
                List<KeyValuePair<string, string>> cookieslist = ControllerContext.HttpContext.Request.Cookies.ToList();
                DateTime myFechaDesdePedida = Convert.ToDateTime("01/01/0001 0:00:00");
                DateTime myFechaHastaPedida = Convert.ToDateTime("01/01/0001 0:00:00");
                int cantidadDePersonas = 0;
                foreach (KeyValuePair<string, string> campos in cookieslist)
                {
                    if (campos.Key.Equals("myCantidadDePersonas"))
                    {
                        cantidadDePersonas = Convert.ToInt32(campos.Value);
                    }
                }
                foreach (KeyValuePair<string, string> campos in cookieslist)
                {
                    if (campos.Key.Equals("myfechaDesde"))
                    {
                        myFechaDesdePedida = Convert.ToDateTime(campos.Value);
                    }
                }
                foreach (KeyValuePair<string, string> campos in cookieslist)
                {
                    if (campos.Key.Equals("myfechaHasta"))
                    {
                        myFechaHastaPedida = Convert.ToDateTime(campos.Value);
                    }
                }
                int dias = myFechaHastaPedida.Day - myFechaDesdePedida.Day;


                ListaOrdenada = mylistaJ.OrderBy(a => (a.precioxDia * dias)).ToList();
            }


            if (ListaOrdenada != null)
            {
                return View("BuscadorAction", ListaOrdenada);
            }
            else
            {
                return NotFound();
                //return View("BuscadorAction", mylistaJ);
            }

        }



        // GET: Alojamiento/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alojamiento = await _context.Alojamiento
                .FirstOrDefaultAsync(m => m.codigo == id);
            if (alojamiento == null)
            {
                return NotFound();
            }

            return View(alojamiento);
        }

        public IActionResult Buscador()
        {
            return View();
        }


        [HttpPost]     
        public IActionResult BuscadorAction(string tipo, string cantPersonasPedidas, string fechaDesde, string fechaHasta, string ciudad)
        {
            DateTime hoy = DateTime.Today;

            ControllerContext.HttpContext.Response.Cookies.Append("myCantidadDePersonas", cantPersonasPedidas);
            ControllerContext.HttpContext.Response.Cookies.Append("myfechaDesde", fechaDesde);
            ControllerContext.HttpContext.Response.Cookies.Append("myfechaHasta", fechaHasta);
            List<Alojamiento> MyLista = null;
            
            List<Reserva> MyListaReservas = null;

            if(!(Convert.ToDateTime(fechaDesde) >= hoy)) // que no acepte fecha anterior
            {
                return RedirectToAction(nameof(Buscador));
            }

            if (tipo == null)
            {
                MyLista = _context.Alojamiento.Where(a => ((a.barrio == ciudad || a.ciudad == ciudad) && (a.cantPersonas >= Convert.ToInt32(cantPersonasPedidas)))).ToList();
            }
            else if (tipo.ToLower() == "hotel" || tipo.ToLower() == "cabaña")
            {
                MyLista = _context.Alojamiento.Where(a => ((a.barrio == ciudad || a.ciudad == ciudad) && (a.tipo == tipo) && (a.cantPersonas >= Convert.ToInt32(cantPersonasPedidas)))).ToList();
            }
            else
            {
                return RedirectToAction(nameof(Buscador));
            }

             MyListaReservas = _context.Reserva.ToList();

           

            
                for (int i = 0; i < MyLista.Count; i++)
                {
                  Console.WriteLine("Mi Count for 1 = " + MyLista.Count + " mi i for 1 = " + i);
                System.Diagnostics.Debug.WriteLine("Mi Count for 1 = "+MyLista.Count+ " mi i for 1 = "+ i );
                    if (MyLista[i].tipo.ToLower() == "cabaña")
                    {
                    Console.WriteLine("Mi Count if = " + MyLista.Count + " mi if  = " + i);
                    System.Diagnostics.Debug.WriteLine("Mi Count if = " + MyLista.Count + " mi if  = " + i);

                    for (int e = 0; e < MyListaReservas.Count; e++)
                        {
                        Console.WriteLine("Mi Count for 2 = " + MyLista.Count + " mi i for 2 = " + i);
                        System.Diagnostics.Debug.WriteLine("Mi Count for 2 = " + MyLista.Count + " mi i for 2 = " + i);

                        System.Diagnostics.Debug.WriteLine(" e " + e);
                        if (Convert.ToInt32(MyListaReservas[e].codigoAlojamiento) == MyLista[i].codigo)
                        { 
                            System.Diagnostics.Debug.WriteLine(" if e 1 " + e);
                            if(((DateTime.Compare(Convert.ToDateTime(fechaDesde), MyListaReservas[e].FDesde) < 0) && (DateTime.Compare(Convert.ToDateTime(fechaHasta), MyListaReservas[e].FDesde) < 0)) || ((DateTime.Compare(Convert.ToDateTime(fechaDesde), MyListaReservas[e].FHasta) > 0) && (DateTime.Compare(Convert.ToDateTime(fechaHasta), MyListaReservas[e].FHasta) > 0)))
                            {
                                System.Diagnostics.Debug.WriteLine(" if e 2 " + e);
                            }
                            else
                            {
                                MyLista.RemoveAt(i);
                                e = MyListaReservas.Count + 1;
                            }
                        }
                       
                        }
                    }
                }
            



            return View(MyLista);
        }
        // GET: Alojamiento/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Alojamiento/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("codigo,tipo,ciudad,barrio,estrellas,cantPersonas,tv,precioxDia,precioxPersona,habitacion,baño,ocupado")] Alojamiento alojamiento)
        {
            if (ModelState.IsValid)
            {
                _context.Add(alojamiento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(alojamiento);
        }

        // GET: Alojamiento/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alojamiento = await _context.Alojamiento.FindAsync(id);
            if (alojamiento == null)
            {
                return NotFound();
            }
            return View(alojamiento);
        }

        // POST: Alojamiento/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

Views/Alojamiento/Buscador.cshtml
@model tpc5FI.Models.Alojamiento


@{
    ViewData["Title"] = "Buscador";
}

<div>
    <a asp-controller="Usuario" asp-action="DetailsUsuario" class="btn btn-primary">Volver</a>
</div>

<h1>Buscador Alojamientos</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="BuscadorAction">
            <div class="form-group">
                Tipo: Cabaña-Hotel
                <input type="text" name="tipo" class="form-control" />
            </div>
            <div class="form-group">
                Ciudad-Barrio
                <input type="text" name="ciudad" class="form-control" required/>
            </div>
            <div class="form-group">
                Cantidad Personas
                <input type="number" min="1" name="cantPersonasPedidas" class="form-control" required />
            </div>
            <div class="form-group">
                Fecha Desde
                <input type="date" name="fechaDesde" class="form-control" required/>
            </div>
            <div class="form-group">
                Fecha Hasta
                <input type="date" name="fechaHasta" class="form-control" required/>
            </div>
            <div>
                <input type="submit" value="Buscar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}


Views/Alojamiento/BuscadorAction.cshtml
@model IEnumerable<tpc5FI.Models.Alojamiento>
@using System.Text.Json;

@{
    ViewData["Title"] = "Resultados";
}


<form asp-controller="Alojamiento" asp-action="filtrar" method="post">

    <select name="filtrar" class="">
        <option value="estrellas" selected>Estrellas</option>
        <option value="cantidadPersonas">CantidadPersonas</option>
        <option value="precioDia">PrecioDia</option>
        <option value="precioPersona">PrecioPersona</option>
        <option value="maxPrecio">MaxPrecio</option>

    </select>

    <input hidden value="@JsonSerializer.Serialize(Model.ToList()).ToString()" name="mylista" />
    <input class="btn btn-primary" type="submit" name="submit" value="filtrar" />
</form>

<h1>Resultados:</h1>
<a asp-action="Buscador" class="btn btn-primary">Buscador</a>

<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ciudad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.barrio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.estrellas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cantPersonas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.precioxDia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.precioxPersona)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.habitacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.baño)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.tipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ciudad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.barrio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.estrellas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cantPersonas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.precioxDia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.precioxPersona)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.habitacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.baño)
                </td>
                <td>
                    <a asp-controller="Reservas" asp-action="Reservar" asp-route-id="@item.codigo" class="btn btn-primary">Reservar</a>
                </td>

            </tr>
        }
    </tbody>
</table>


Views/Alojamiento/Create.cshtml
@model tpc5FI.Models.Alojamiento

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Alojamiento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="tipo" class="control-label"></label>
                <input asp-for="tipo" class="form-control" />
                <span asp-validation-for="tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ciudad" class="control-label"></label>
                <input asp-for="ciudad" class="form-control" />
                <span asp-validation-for="ciudad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="barrio" class="control-label"></label>
                <input asp-for="barrio" class="form-control" />
                <span asp-validation-for="barrio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="estrellas" class="control-label"></label>
                <input asp-for="estrellas" class="form-control" />
                <span asp-validation-for="estrellas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cantPersonas" class="control-label"></label>
                <input asp-for="cantPersonas" class="form-control" />
                <span asp-validation-for="cantPersonas" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="tv" /> @Html.DisplayNameFor(model => model.tv)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="precioxDia" class="control-label"></label>
                <input asp-for="precioxDia" min="1" class="form-control" />
                
            </div>
            <div class="form-group">
                <label asp-for="precioxPersona" class="control-label"></label>
                <input asp-for="precioxPersona" min="1" class="form-control" />
                
            </div>
            <div class="form-group">
                <label asp-for="habitacion" class="control-label"></label>
                <input asp-for="habitacion" class="form-control" />
                
            </div>
            <div class="form-group">
                <label asp-for="baño" class="control-label"></label>
                <input asp-for="baño" class="form-control" />
                
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary">Volver a Alojamientos</a>
</div>



Views/Alojamiento/Delete.cshtml
@model tpc5FI.Models.Alojamiento

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>

<h3>Estas seguro de eliminar este Alojamiento?</h3>
<div>
    <h4>Alojamiento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ciudad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ciudad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.barrio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.barrio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.estrellas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estrellas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cantPersonas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cantPersonas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.precioxDia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.precioxDia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.precioxPersona)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.precioxPersona)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.habitacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.habitacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.baño)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.baño)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="codigo" />
        <input type="submit" value="Eliminar" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-primary">Cancelar</a>
    </form>
</div>

Views/Alojamiento/Details.cshtml
@model tpc5FI.Models.Alojamiento

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>

<div>
    <h4>Alojamiento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ciudad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ciudad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.barrio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.barrio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.estrellas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estrellas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cantPersonas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cantPersonas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.precioxDia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.precioxDia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.precioxPersona)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.precioxPersona)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.habitacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.habitacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.baño)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.baño)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.codigo" class="btn btn-primary">Editar</a> |
    <a asp-action="Index" class="btn btn-primary">Volver a Alojamientos</a>
</div>

Views/Alojamiento/Edit.cshtml
@model tpc5FI.Models.Alojamiento

@{
    ViewData["Title"] = "Editar Alojamiento";
}

<h1>Editar</h1>

<h4>Alojamiento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="codigo" />
            <div class="form-group">
                <label asp-for="tipo" class="control-label"></label>
                <input asp-for="tipo" class="form-control" />
                <span asp-validation-for="tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ciudad" class="control-label"></label>
                <input asp-for="ciudad" class="form-control" />
                <span asp-validation-for="ciudad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="barrio" class="control-label"></label>
                <input asp-for="barrio" class="form-control" />
                <span asp-validation-for="barrio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="estrellas" class="control-label"></label>
                <input asp-for="estrellas" class="form-control" />
                <span asp-validation-for="estrellas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cantPersonas" class="control-label"></label>
                <input asp-for="cantPersonas" class="form-control" />
                <span asp-validation-for="cantPersonas" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="tv" /> @Html.DisplayNameFor(model => model.tv)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="precioxDia" class="control-label"></label>
                <input asp-for="precioxDia" min="1" class="form-control" />
                <span asp-validation-for="precioxDia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="precioxPersona" class="control-label"></label>
                <input asp-for="precioxPersona" min="1" class="form-control" />
                <span asp-validation-for="precioxPersona" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="habitacion" class="control-label"></label>
                <input asp-for="habitacion" class="form-control" />
                <span asp-validation-for="habitacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="baño" class="control-label"></label>
                <input asp-for="baño" class="form-control" />
                <span asp-validation-for="baño" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar cambios" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"class="btn btn-danger">Cancelar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Alojamiento/Index.cshtml
@model IEnumerable<tpc5FI.Models.Alojamiento>

@{
    ViewData["Title"] = "Alojamientos";
}

<h1>Alojamientos</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Agregar Alojamiento</a>
    <a asp-controller="Usuario" asp-action="Index" class="btn btn-primary">Volver Usuarios</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ciudad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.barrio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.estrellas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cantPersonas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.precioxDia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.precioxPersona)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.habitacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.baño)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.tipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ciudad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.barrio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.estrellas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantPersonas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precioxDia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precioxPersona)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.habitacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.baño)
            </td>
            <td class="my-2">
                <a asp-action="Edit" asp-route-id="@item.codigo" class="btn btn-primary my-1">Editar</a> 
                <a asp-action="Details" asp-route-id="@item.codigo" class="btn btn-primary my-1">Detalles</a> 
                <a asp-action="Delete" asp-route-id="@item.codigo" class="btn btn-danger my-1">Eliminar</a> 
            </td>
        </tr>
}
    </tbody>
</table>