Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace tpc5FI.Models
{
	public class Usuario 
	{	[Key]
		public int usuarioID { get; set; }
		[Display(Name = "Documento")]
		[Required(ErrorMessage = "Este campo es requerido")]
		public int dni { get; set; }
		[Display(Name = "Nombre")]
		[Required(ErrorMessage = "Este campo es requerido")]
		public string nombre { get; set; }
		[Display(Name = "Email")]
		[Required(ErrorMessage = "Este campo es requerido")]
		public string mail { get; set; }
		[Display(Name = "Contraseña")]
		[Required(ErrorMessage = "Este campo es requerido")]
		public string password { get; set; }
		[Display(Name = "Es Administrador")]
		public bool esAdmin { get; set; }
		[Display(Name = "Bloqueado")]
		public bool bloqueado { get; set; }

		public int cant_intentos { get; set; }


		public Usuario()
		{

		}

		public Usuario(int dni, string nombre, string mail, string password, bool admin, bool bloqueado, int cant_intentos)
		{
			this.dni = dni;
			this.nombre = nombre;
			this.mail = mail;
			this.password = password;
			esAdmin = admin;
			this.bloqueado = bloqueado;
			this.cant_intentos = cant_intentos;
		}

		public int getDNI()
		{
			return dni;
		}

		public int getCodigo()
		{
			return usuarioID;
		}

		public String getNombre()
		{
			return nombre;
		}

		public String getMail()
		{
			return mail;
		}

		public String getPassword()
		{
			return password;
		}
		
		public bool getBloqueado()
		{
			return bloqueado;
		}

		public bool getAdmin()
		{
			return esAdmin;
		}

		public void setBloqueado()
		{
			if (bloqueado == false)
			{
				bloqueado = true;

			}
			else if (bloqueado == true)
			{
				bloqueado = false;

			}

		}
		public void setAdmin()
		{
			if (esAdmin == false)
			{
				esAdmin = true;

			}
			else if (esAdmin == true)
			{
				esAdmin = false;

			}

		}

		public void setDNI(int dni)
		{
			this.dni = dni;
		}

		public void setNombre(String nombre)
		{
			this.nombre = nombre;
		}

		public void setPassword(String password)
		{
			this.password = password;
		}

		public void setMail(String mail)
		{
			this.mail = mail;
		}

	}
}

Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tp5Fi.Data;
using tpc5FI.Models;

namespace tp5Fi.Models
{
    public class ReservasController : Controller
    {       
        private readonly MyContext _context;

        public ReservasController(MyContext context)
        {
            _context = context;
        }

        // GET: Reservas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Reserva.ToListAsync());
        }

        public IActionResult Reservar(int id)
        {
            int idAlojamiento = id;
            int idUsuario = 0;
            if (idAlojamiento > 0)
            {
                List<KeyValuePair<string, string>> cookieslist = ControllerContext.HttpContext.Request.Cookies.ToList();
                foreach (KeyValuePair<string, string> campos in cookieslist)
                {
                    if (campos.Key.Equals("myUsuario"))
                    {
                        idUsuario = Convert.ToInt32(campos.Value);
                    }
                }
                //int idUsuario =Convert.ToInt32( HttpContext.Request.HttpContext.Items["key"]); //agarrar la "cookie"
                /*fecha desde + fecha despues
                 precioxdia * cantidad de personas * dias Hotel
                precioxdia * dias  Cabaña
                  
                 */
                DateTime myFechaDesdePedida = Convert.ToDateTime("01/01/0001 0:00:00");
                DateTime myFechaHastaPedida = Convert.ToDateTime("01/01/0001 0:00:00");
                int cantidadDePersonas = 0;
                if (idUsuario > 0)
                {
                    var alojamiento = _context.Alojamiento.First(a => a.codigo == idAlojamiento);
                    Reserva reserva = null;

                    if (alojamiento.tipo.ToLower() == "hotel")
                    {

                        foreach (KeyValuePair<string, string> campos in cookieslist)
                        {
                            if (campos.Key.Equals("myCantidadDePersonas"))
                            {
                                cantidadDePersonas = Convert.ToInt32(campos.Value);
                            }
                        }
                        foreach (KeyValuePair<string, string> campos in cookieslist)
                        {
                            if (campos.Key.Equals("myfechaDesde"))
                            {
                                myFechaDesdePedida = Convert.ToDateTime(campos.Value);
                            }
                        }
                        foreach (KeyValuePair<string, string> campos in cookieslist)
                        {
                            if (campos.Key.Equals("myfechaHasta"))
                            {
                                myFechaHastaPedida = Convert.ToDateTime(campos.Value);
                            }
                        }
                        int dias = myFechaHastaPedida.Day - myFechaDesdePedida.Day;
                        dias++;
                        double precio = alojamiento.precioxDia * dias * (cantidadDePersonas * alojamiento.precioxPersona) ;

                        System.Diagnostics.Debug.WriteLine("mi nombree ciudad " + alojamiento.ciudad);
                        reserva = new Reserva(myFechaDesdePedida, myFechaHastaPedida, idAlojamiento, idUsuario, Convert.ToSingle(precio), alojamiento.ciudad);
                        return RedirectToAction("DetailsReserva", reserva);
                    }
                    else if (alojamiento.tipo.ToLower() == "cabaña")
                    {
                        System.Diagnostics.Debug.WriteLine("mi cabaña ciudad " + alojamiento.ciudad);
                        foreach (KeyValuePair<string, string> campos in cookieslist)
                        {
                            if (campos.Key.Equals("myfechaDesde"))
                            {
                                myFechaDesdePedida = Convert.ToDateTime(campos.Value);
                            }
                        }
                        foreach (KeyValuePair<string, string> campos in cookieslist)
                        {
                            if (campos.Key.Equals("myfechaHasta"))
                            {
                                myFechaHastaPedida = Convert.ToDateTime(campos.Value);
                            }
                        }

                        int dias = myFechaHastaPedida.Day - myFechaDesdePedida.Day;
                        double precio = alojamiento.precioxDia * dias; 
                        reserva = new Reserva(myFechaDesdePedida, myFechaHastaPedida, idAlojamiento, idUsuario, Convert.ToSingle(precio), alojamiento.ciudad);

                        return RedirectToAction("DetailsReserva", reserva);
                    }

                }
                else
                {
                    return NotFound();
                }
            }
            return RedirectToAction(nameof(Index));
        }
        // GET: Reservas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {

                return NotFound();
            }

            var reserva = await _context.Reserva
                .FirstOrDefaultAsync(m => m.id == id);
            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }

        public  IActionResult DetailsReserva(Reserva reserva)
        {           
            return View(reserva);
        }

        public IActionResult DetailsReservaUsuario()
        {
            List<KeyValuePair<string, string>> cookieslist = ControllerContext.HttpContext.Request.Cookies.ToList();
            int myUsuario = 0;
            foreach (KeyValuePair<string, string> campos in cookieslist)
            {
                if (campos.Key.Equals("myUsuario"))
                {
                    myUsuario = Convert.ToInt32(campos.Value);
                }
            }

            List<Reserva> reserva = _context.Reserva.Where(m => m.codigoPersona == myUsuario).ToList();
                
            if (reserva == null)
            {
                return View();
            }

            return View(reserva);
        }

        // GET: Reservas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Reservas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FDesde,FHasta,codigoAlojamiento,codigoPersona,precio,nombreAlojamiento")] Reserva reserva)
        {
            System.Diagnostics.Debug.WriteLine("fDesde "+ reserva.FDesde+ "fhasta "+ reserva.FHasta + "codigo alojamiento " + reserva.codigoAlojamiento+ "codigo persona " + reserva.codigoPersona+ "precio "+ reserva.precio+ "nombre alojamiento" + reserva.nombreAlojamiento);
            if (ModelState.IsValid)
            {
                
                
                Alojamiento aloj = await _context.Alojamiento.FirstAsync(a => a.codigo == reserva.codigoAlojamiento);
                if (aloj.tipo.ToLower() == "hotel")
                {
                    List<KeyValuePair<string, string>> cookieslist = ControllerContext.HttpContext.Request.Cookies.ToList();                    
                    int cantidadDePersonas = 0;
                    foreach (KeyValuePair<string, string> campos in cookieslist)
                    {
                        if (campos.Key.Equals("myCantidadDePersonas"))
                        {
                            cantidadDePersonas = Convert.ToInt32(campos.Value);
                        }
                    }

                    if (cantidadDePersonas > 0)
                    {
                        aloj.cantPersonas = aloj.cantPersonas - cantidadDePersonas;
                        _context.Update(aloj);
                    }
                    else
                    {
                        return NotFound();
                    }
                }
                _context.Add(reserva);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(DetailsReservaUsuario));
            }
            return NotFound();
        }

        // GET: Reservas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reserva.FindAsync(id);
            if (reserva == null)
            {
                return NotFound();
            }
            return View(reserva);
        }

        // POST: Reservas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,FDesde,FHasta,codigoAlojamiento,codigoPersona,precio")] Reserva reserva)
        {
            if (id != reserva.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reserva);
                    await _context.SaveChangesAsync();
                }

Views/Usuario/Create.cshtml
@model tpc5FI.Models.Usuario

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="dni" class="control-label"></label>
                <input asp-for="dni" class="form-control" required />
                <span asp-validation-for="dni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" required />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mail" class="control-label"></label>
                <input asp-for="mail" class="form-control" required />
                <span asp-validation-for="mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="password" class="control-label"></label>
                <input asp-for="password" class="form-control" required />
                <span asp-validation-for="password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="esAdmin" class="control-label">
                    <input asp-for="esAdmin" class="form-check-input" /> @Html.DisplayNameFor(model => model.esAdmin)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="bloqueado" class="control-label">
                    <input asp-for="bloqueado" class="form-check-input" /> @Html.DisplayNameFor(model => model.bloqueado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index" class="btn btn-danger">Cancelar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Usuario/CreateUsuario.cshtml
@model tpc5FI.Models.Usuario

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input hidden class="form-check-input" asp-for="bloqueado" />
            <input hidden class="form-check-input" asp-for="bloqueado" />
            <div class="form-group">
                <label asp-for="dni" class="control-label"></label>
                <input asp-for="dni" class="form-control" required />
                <span asp-validation-for="dni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" required/>
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mail" class="control-label"></label>
                <input asp-for="mail" class="form-control" required/>
                <span asp-validation-for="mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="password" class="control-label"></label>
                <input asp-for="password" class="form-control" required/>
                <span asp-validation-for="password" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Usuario/Delete.cshtml
@model tpc5FI.Models.Usuario

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Esta seguro de eliminar este Usuario?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.esAdmin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.esAdmin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.bloqueado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.bloqueado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="usuarioID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-primary">Index Usuarios</a>
    </form>
</div>

Views/Usuario/Details.cshtml
@model tpc5FI.Models.Usuario

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.esAdmin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.esAdmin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.bloqueado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.bloqueado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.usuarioID" class="btn btn-primary">Editar</a> |
    <a asp-action="Index" class="btn btn-primary">Index Usuarios</a>
    
</div>

Views/Usuario/DetailsUsuario.cshtml
@model tpc5FI.Models.Usuario

@{
    ViewData["Title"] = "Detalle ";
}

<h1>Detalles</h1>



<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.esAdmin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.esAdmin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.bloqueado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.bloqueado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="EditUsuario" asp-route-id="@Model.usuarioID" class="btn btn-primary">Editar</a> 
    <a asp-controller="Alojamiento" asp-action="Buscador" class="btn btn-primary">Buscador Alojamientos</a> 
    <a asp-controller="Reservas" asp-action="DetailsReservaUsuario" class="btn btn-primary">Mis Reservas</a>
</div>

Views/Usuario/Edit.cshtml
@model tpc5FI.Models.Usuario

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="usuarioID" />
            <div class="form-group">
                <label asp-for="dni" class="control-label"></label>
                <input asp-for="dni" class="form-control" />
                <span asp-validation-for="dni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mail" class="control-label"></label>
                <input asp-for="mail" class="form-control" />
                <span asp-validation-for="mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="password" class="control-label"></label>
                <input asp-for="password" class="form-control" />
                <span asp-validation-for="password" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="esAdmin" /> @Html.DisplayNameFor(model => model.esAdmin)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="bloqueado" /> @Html.DisplayNameFor(model => model.bloqueado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar Cambios" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-danger">Cancelar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Usuario/EditUsuario.cshtml
@model tpc5FI.Models.Usuario

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditUsuario">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="usuarioID" />
            <input type="hidden" asp-for="esAdmin" />
            <input type="hidden" asp-for="bloqueado" />
            <div class="form-group">
                <label asp-for="dni" class="control-label"></label>
                <input asp-for="dni" class="form-control" />
                <span asp-validation-for="dni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mail" class="control-label"></label>
                <input asp-for="mail" class="form-control" />
                <span asp-validation-for="mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="password" class="control-label"></label>
                <input asp-for="password" class="form-control" />
                <span asp-validation-for="password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar Cambios" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="DetailsUsuario" asp-route-id=@Model.usuarioID class="btn btn-danger">Cancelar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Usuario/Index.cshtml
@model IEnumerable<tpc5FI.Models.Usuario>

@{
    ViewData["Title"] = "Usuarios";
}

<h1>Usuarios</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Crear Usuario</a>
    <a asp-area="" asp-controller="Alojamiento" asp-action="Index" class="btn btn-primary">Alojamientos</a>
    <a asp-area="" asp-controller="Reservas" asp-action="Index" class="btn btn-primary">Reservas</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.dni)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.esAdmin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bloqueado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.dni)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.password)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.esAdmin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.bloqueado)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.usuarioID" class="btn btn-primary">Editar</a> 
                    <a asp-action="Details" asp-route-id="@item.usuarioID" class="btn btn-primary">Detalles</a> 
                    <a asp-action="Delete" asp-route-id="@item.usuarioID" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Usuario/Login.cshtml
@model tpc5FI.Models.Usuario

@{
    ViewData["Title"] = "Login";
}

<div class="text-center">
    <h1 class="display-4 font-weight-bold">Inicio Sesion</h1>
    <img src="/images/logo_login.png" width="200" height="300" alt="login" class="img-fluid  pt-3">
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="usuarioID" />
            <input type="hidden" asp-for="esAdmin" />
            <input type="hidden" asp-for="bloqueado" />
            <input type="hidden" asp-for="nombre" />
            <input type="hidden" asp-for="mail" />
            <div class="form-group">
                <label asp-for="dni" class="control-label"></label>
                <input asp-for="dni" class="form-control"  required />
                <span asp-validation-for="dni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="password" class="control-label"></label>
                <input asp-for="password" class="form-control" required/>
                <span asp-validation-for="password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Ingresar" class="btn btn-primary" />
            </div>
        </form>
        <a class="btn btn-primary" asp-area="" asp-controller="Usuario" asp-action="CreateUsuario">Nuevo Usuario</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}